#package(default_visibility = ["//src:snip"])

cc_library(
  name = "snip",
  srcs = glob(["*.cpp"]),
  hdrs = glob(["*.h"]),
  #deps = ["@entangled/cclient:api",],
  visibility = ["//cli:__pkg__", "//test:__pkg__"]
)